version: 1.2

workflows:
  - name: RSV_pe_assembly
    subclass: WDL
    primaryDescriptorPath: /workflows/RSV_pe_assembly.wdl
  - name: RSV_pe_transfer
    subclass: WDL
    primaryDescriptorPath: /workflows/RSV_pe_transfer.wdl

