version: 1.2

workflows:
  - name: RSV_illumina_pe_assembly
    subclass: WDL
    primaryDescriptorPath: /workflows/RSV_illumina_pe_assembly.wdl
  - name: RSV_illumina_pe_summary
    subclass: WDL
    primaryDescriptorPath: /workflows/RSV_illumina_pe_summary.wdl
