name: rsv_wdl
channels:
  - defaults
  - conda-forge
dependencies:
  - google-cloud-sdk=506.0.0
  - miniwdl=1.12.1
  - python=3.11.9
  - pip=24.0
  - pip:
    - biopython==1.85
    - pandas==2.1.3
    - ruff==0.7.*
