name: Code Analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff mypy pandas-stubs bio
    - name: Analyze code with ruff
      run: ruff check .
    - name: Check code format with ruff
      run: ruff format --check .
    - name: Analyze code with mypy
      run: mypy ./scripts/concat_seq_results.py
